include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "**/.dart_tool/**"
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error
    override_on_non_overriding_member: error
    unnecessary_null_comparison: error
    invalid_null_aware_operator: error
    deprecated_member_use_from_same_package: warning

linter:
  rules:
    public_member_api_docs: false

dart_code_metrics:
  rules:
    - avoid-banned-imports:
        entries:
          - paths:
              - '^app/lib/'
            deny:
              - '^package:stripe'
              - '^package:stripe_sdk'
              - '^package:geolocator'
              - '^package:google_maps_flutter'
              - '^package:flutter_background_geolocation'
              - '^package:firebase_messaging'
              - '^package:http/http\\.dart$'
              - '^package:location'
              - '^package:permission_handler'
            message: 'B-STYLE violation: Direct SDK import not allowed in app/lib. Use shims instead.'
